version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: andorralee-mysql-win
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=andorralee
    restart: unless-stopped

  andorralee:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: andorralee-win
    ports:
      - "8848:8848"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=andorralee
    restart: unless-stopped

volumes:
  mysql_data: 
